
services:
  app:
    build: .
    container_name: runic_arena_app
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      APP_ENV: prod
      DATABASE_URL: "mysql://laura:laura1409@db:3306/runic_arena"
  db:
    container_name: runic_arena_db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: runic_arena
      MYSQL_USER: laura
      MYSQL_PASSWORD: laura1409
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default
  
  adminer:
    container_name: runic_arena_adminer
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
    networks:
      - default
    restart: unless-stopped
    ports:
      - 8080:8080

networks:
  default:
    name: runic_arena_net
    driver: bridge

volumes:
  db_data:
